#!/usr/bin/python3 -cimport os, sys; os.execv(os.path.dirname(sys.argv[1]) + "/common/pywrap", sys.argv)

import testlib


@testlib.nondestructive
class TestApplication(testlib.MachineCase):
    def testNavigation(self):
        b = self.browser

        self.login_and_go("/openssh")

        # The server page is the default route.
        b.wait_text(".pf-v6-c-card__title", "SSH daemon")
        b.wait_in_text("#ssh-Port", "")

        b.click(".pf-v6-c-nav__link:contains('Authorized keys')")
        b.wait_visible("#ssh-account")
        b.wait_visible("button:contains('Add client')")

        b.click(".pf-v6-c-nav__link:contains('Known hosts')")
        b.wait_visible("#ssh-known-hosts-file")
        b.wait_visible("#ssh-report-enabled")

    def testDropInIsValidatedBeforeReload(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/openssh")
        b.wait_text(".pf-v6-c-card__title", "SSH daemon")

        # An invalid directive must be rejected by "sshd -t" and rolled back,
        # leaving the daemon untouched.
        b.click(".pf-v6-c-expandable-section__toggle")
        b.set_input_text("#ssh-raw", "ThisIsNotADirective yes\n")
        b.click("button:contains('Apply and reload')")
        b.wait_in_text(".pf-v6-c-alert__title", "Error")

        m.execute("test ! -s /etc/ssh/sshd_config.d/00-cockpit-openssh.conf")
        m.execute("/usr/sbin/sshd -t")


if __name__ == '__main__':
    testlib.test_main()
