name: tasks-container-update
on:
  schedule:
    - cron: '0 2 * * 1'
  # can be run manually on the Actions tab of this repository
  workflow_dispatch:
jobs:
  tasks-container-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      statuses: write
    container:
      image: ghcr.io/cockpit-project/tasks
      options: --user root
    steps:
      - name: Set up configuration and secrets
        run: |
          printf '[user]\n\tname = Cockpit Project\n\temail=cockpituous@gmail.com\n' > ~/.gitconfig
          mkdir -p ~/.config
          echo '${{ secrets.GITHUB_TOKEN }}' > ~/.config/github-token

      - name: Clone repository
        uses: actions/checkout@v6

      # https://github.blog/2022-04-12-git-security-vulnerability-announced/
      - name: Pacify git's permission check
        run: git config --global --add safe.directory /__w/cockpit-applications/cockpit-applications

      - name: Run tasks-container-update (cockpit-git-server)
        working-directory: cockpit-git-server
        run: |
          make bots
          bots/tasks-container-update

      - name: Run tasks-container-update (cockpit-backup)
        working-directory: cockpit-backup
        run: |
          make bots
          bots/tasks-container-update

      - name: Run tasks-container-update (cockpit-security)
        working-directory: cockpit-security
        run: |
          make bots
          bots/tasks-container-update

      - name: Run tasks-container-update (cockpit-openssh)
        working-directory: cockpit-openssh
        run: |
          make bots
          bots/tasks-container-update
